on: [push]
name: Install via script
jobs:
    install-ubuntu:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@master
            -   run: echo 1 | ./project-base/scripts/install.sh
